version: "3.8"

services:
  org-project-api-01:
    container_name: org-project-api-01
    restart: always
    environment:
      API_PORT: ${API_PORT}
      API_TOKEN: ${API_TOKEN}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      TZ: ${TZ}
    build:
      context: ./api-01
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT}
#    ports: 
#      - 8080:${API_PORT}
    networks:
      - org-project

  org-project-ui-01:
    container_name: org-project-ui-01
    restart: always
    environment:
      UI_PORT: ${UI_PORT}
      API_HOST: ${API_HOST}
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        UI_PORT: ${UI_PORT}
#    ports:
#      - 8081:${API_PORT}
    networks:
      - org-project

  org-project-duckdns:
    container_name: org-project-duckdns
    restart: always
    image: ghcr.io/linuxserver/duckdns
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SUBDOMAINS: ${SUBDOMAINS}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
      LOG_FILE: ${LOG_FILE}
    networks:
      - org-project

  org-project-db:
    container_name: org-project-db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: ${TZ}
    volumes:
      - ../db:/var/lib/postgresql/data
    networks:
      - org-project

  org-project-pgadmin:
    container_name: org-project-pgadmin
    restart: always
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - org-project-db
#    ports: 
#      - 8082:80
    networks:
      - org-project

networks:
  org-project:
    name: org-project
